#本服务端口配置
server:
  port: 8787

#服务名称配置
spring:
  application:
    name: server2


#中间件注册中心配置
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5   #心跳间隔设置  5秒
    lease-expiration-duration-in-seconds: 10  #没有心跳的淘汰时间设计 10秒
  client:
    service-url:
      defaultZone: http://yw:yw@localhost:8888/eureka/  #中间件注册中心配置，默认使用用户密码登录
    registry-fetch-interval-seconds: 5  #定时刷新本地环境时间设置


logging:
  level:
    com.app: DEBUG